### ISSUE TITLE
Manifest references pluginIcon but it is not there

### ISSUE THREAD

**Issue by Phando** [elgatosf/sample-clock-plugin#1]
I am trying a fresh start on my plugin using this clock demo as my base. The manifest is referencing pluginIcon but it is nowhere to be found in the sample repo. Can you please point me in the right direction?

**Comment by tiptronic** [comment]
The icon is needed, if you want to release the plugin to the store.

Since this is only a SDK-sample it doesn't need a store icon and therefore it's not included - but you can just drop an image into the plugin's folder (72x72px and 144x144px) and add the name into the 'icon' field of the manifest.

https://developer.elgato.com/documentation/stream-deck/sdk/manifest/

**Comment by tiptronic** [comment]
I added a plugin-icon (and a .sketch source-file)
